"""initial tables 2

Revision ID: 15404a4e00e8
Revises: e5e4cb4e5e8a
Create Date: 2026-09-26 17:16:01.238726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15404a4e00e8'
down_revision: Union[str, Sequence[str], None] = 'e5e4cb4e5e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('max_user_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'VIEWER', name='adminrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_user_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'APPROVED', 'RUNNING', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('csv_file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('segment_group', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('clients_count', sa.Integer(), nullable=False),
    sa.Column('avg_recency', sa.Float(), nullable=False),
    sa.Column('avg_frequency', sa.Float(), nullable=False),
    sa.Column('avg_monetary_score', sa.Float(), nullable=False),
    sa.Column('avg_amount', sa.Float(), nullable=False),
    sa.Column('proposed_bonus', sa.Integer(), nullable=False),
    sa.Column('final_bonus', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cat_campaign', 'campaign_categories', ['campaign_id'], unique=False)
    op.create_table('bonus_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('external_txn_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCRUED', 'USED', 'EXPIRED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['campaign_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_txn_id')
    )
    op.create_index('idx_txn_category', 'bonus_transactions', ['category_id'], unique=False)
    op.create_index('idx_txn_external', 'bonus_transactions', ['external_txn_id'], unique=False)
    op.create_index('idx_txn_status_expires', 'bonus_transactions', ['status', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_txn_status_expires', table_name='bonus_transactions')
    op.drop_index('idx_txn_external', table_name='bonus_transactions')
    op.drop_index('idx_txn_category', table_name='bonus_transactions')
    op.drop_table('bonus_transactions')
    op.drop_index('idx_cat_campaign', table_name='campaign_categories')
    op.drop_table('campaign_categories')
    op.drop_table('campaigns')
    op.drop_table('business_admins')
    # ### end Alembic commands ###
